#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# Copyright (C) 2020 LemoFire <https://www.ito.fun>
#
# <https://github.com/P3TERX/Actions-OpenWrt>
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/LemoFire/autoOpenWrt>
#

name: NEWIFI-D2

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#  schedule:
#    - cron: 0 */12 * * *
#  watch:
#    types: started



jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update -yqq
          sudo apt full-upgrade -yqq
          sudo apt install -yqq ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
      - name: Download lede
        run: |
          git clone https://github.com/coolsnowwolf/lede
          mv ./lede/* ./
      - name: Install addons
        run: |
          echo "src-git helloworld https://github.com/fw876/helloworld" >> ./feeds.conf.default 
          git clone https://github.com/kiddin9/openwrt-packages.git
          cd package
          mkdir openwrt-packages
          mv ../openwrt-packages/luci-app-aliddns openwrt-packages/luci-app-aliddns
          mv ../openwrt-packages/luci-app-eqos openwrt-packages/luci-app-eqos
          mv ../openwrt-packages/luci-app-wolplus openwrt-packages/luci-app-wolplus
          cd lean
          rm -rf luci-theme-argon  
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Costom configure file
        run: |
          sed -i 's/luci-theme-bootstrap/luci-theme-argon/g' feeds/luci/collections/luci/Makefile
          # sed -i 's/country=US/country=CN/g' package/kernel/mac80211/files/lib/wifi/mac80211.sh
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          # Device type
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_d-team_newifi-d2=y
          CONFIG_TARGET_IMAGES_GZIP=y

          # IPv6
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y

          # Storage
          CONFIG_PACKAGE_autosamba=n
          CONFIG_PACKAGE_kmod-usb3=y
          CONFIG_PACKAGE_automount=y


          # APP
          CONFIG_PACKAGE_luci-app-aria2=n
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-frpc=n
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-openvpn=n
          CONFIG_PACKAGE_luci-app-openvpn-server=n
          CONFIG_PACKAGE_luci-app-qos=y
          CONFIG_PACKAGE_luci-app-syncdial=n
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-turboacc=y
          CONFIG_PACKAGE_luci-app-usb-printer=n
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-vlmcsd=n
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          CONFIG_PACKAGE_luci-app-xlnetacc=n
          CONFIG_PACKAGE_luci-app-zerotier=n
          CONFIG_PACKAGE_vsftpd-alt=n
          CONFIG_PACKAGE_luci-app-vsftpd=n
          CONFIG_PACKAGE_luci-i18n-vsftpd-zh-cn=n
          CONFIG_PACKAGE_luci-app-unbound=y
          CONFIG_PACKAGE_unbound-checkconf=y
          CONFIG_PACKAGE_unbound-control=y
          CONFIG_PACKAGE_unbound-control-setup=y
          CONFIG_PACKAGE_unbound-host=y
          CONFIG_PACKAGE_bind-tools=y
          CONFIG_PACKAGE_bind-nslookup=y
          CONFIG_PACKAGE_bind-check=y
          CONFIG_PACKAGE_bind-client=y
          CONFIG_PACKAGE_bind-dig=y
          CONFIG_PACKAGE_bind-dnssec=y
          CONFIG_PACKAGE_bind-host=y
          CONFIG_PACKAGE_bind-libs=y
          CONFIG_PACKAGE_ss=y
          CONFIG_PACKAGE_ddns-scripts_cloudflare.com-v4=y
          CONFIG_PACKAGE_ddns-scripts_freedns_42_pl=y
          CONFIG_PACKAGE_ddns-scripts_no-ip_com=y
          CONFIG_PACKAGE_ddns-scripts_nsupdate=y
          CONFIG_PACKAGE_ddns-scripts_route53-v1=y
          CONFIG_PACKAGE_kmod-fs-nfs=y
          CONFIG_PACKAGE_kmod-fs-nfs-common=y
          CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_ip6tables-extra=y
          CONFIG_PACKAGE_ip6tables-mod-nat=y
          CONFIG_PACKAGE_kmod-ip6tables=y
          CONFIG_PACKAGE_kmod-ip6tables-extra=y
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_6rd=y
          CONFIG_PACKAGE_6to4=y
          CONFIG_PACKAGE_attr=y
          CONFIG_PACKAGE_iptables-mod-hashlimit=y
          CONFIG_PACKAGE_iptables-mod-ipmark=y
          CONFIG_PACKAGE_iptables-mod-account=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-ipsec=y
          CONFIG_PACKAGE_kmod-nf-ipt=y
          CONFIG_PACKAGE_kmod-nf-ipt6=y
          CONFIG_PACKAGE_kmod-nf-nat=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-ipt-ipsec=y
          CONFIG_PACKAGE_kmod-ipt-ipset=y
          CONFIG_PACKAGE_kmod-ipt-nat=y
          CONFIG_PACKAGE_kmod-ipt-nat-extra=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-ipt-offload=y
          CONFIG_PACKAGE_kmod-ipt-raw=y
          CONFIG_PACKAGE_kmod-ipt-tproxy=y
          CONFIG_PACKAGE_kmod-ipt-u32=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-nf-flow=y
          CONFIG_PACKAGE_kmod-mpls=y
          CONFIG_PACKAGE_kmod-nf-conntrack=y
          CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
          CONFIG_PACKAGE_kmod-nf-conntrack6=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_libcurl4=y
          CONFIG_PACKAGE_iptables-mod-nat-extra=y
          CONFIG_PACKAGE_hostip=y
          CONFIG_PACKAGE_ip-bridge=y
          CONFIG_PACKAGE_ipip=y
          CONFIG_PACKAGE_iptables-mod-u32=y
          CONFIG_PACKAGE_kmod-ipip=y
          CONFIG_PACKAGE_kmod-ipsec=y
          CONFIG_PACKAGE_kmod-ipt-condition=y
          CONFIG_PACKAGE_kmod-nft-core=y
          CONFIG_PACKAGE_kmod-openvswitch=y
          CONFIG_PACKAGE_libevent2-core7=y
          CONFIG_PACKAGE_libevent2-pthreads7=y
          CONFIG_PACKAGE_libgd=y
          CONFIG_PACKAGE_libsodium=y
          CONFIG_PACKAGE_libreadline8=y
          CONFIG_PACKAGE_luasocket=y
          CONFIG_PACKAGE_luci-app-ntpc=y
          CONFIG_PACKAGE_luci-app-uhttpd=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-i18n-ntpc-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-uhttpd-zh-cn=y
          CONFIG_PACKAGE_luci-lib-httpclient=y
          CONFIG_PACKAGE_luci-mod-system=y
          CONFIG_PACKAGE_luci-mod-network=y
          CONFIG_PACKAGE_luci-proto-ipip=y
          CONFIG_PACKAGE_luci-mod-status=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_nfs-utils=y
          CONFIG_PACKAGE_ntpclient=y
          CONFIG_PACKAGE_openvswitch=y
          CONFIG_PACKAGE_openvswitch-common=y
          CONFIG_PACKAGE_openvswitch-libofproto=y
          CONFIG_PACKAGE_openvswitch-libopenvswitch=y
          CONFIG_PACKAGE_openvswitch-libovsdb=y
          CONFIG_PACKAGE_openvswitch-ovsdb=y
          CONFIG_PACKAGE_openvswitch-vswitchd=y
          CONFIG_PACKAGE_luci-proto-relay=y
          CONFIG_PACKAGE_pppoe-discovery=y
          CONFIG_PACKAGE_relayd=y
          CONFIG_PACKAGE_resolveip=y
          CONFIG_PACKAGE_rpcbind=y
          CONFIG_PACKAGE_rpcd-mod-file=y
          CONFIG_PACKAGE_rpcd-mod-iwinfo=y
          CONFIG_PACKAGE_rpcd-mod-luci=y
          CONFIG_PACKAGE_tcpbridge=y
          CONFIG_PACKAGE_tcpdump=y
          CONFIG_PACKAGE_uuid=y
          CONFIG_PACKAGE_uuidgen=y
          CONFIG_PACKAGE_wget=y
          CONFIG_PACKAGE_vpnc=y
          CONFIG_PACKAGE_vpnc-scripts=y
          CONFIG_PACKAGE_wireless-regdb=y
          

          # Third party packages
          CONFIG_PACKAGE_luci-app-aliddns=n
          CONFIG_PACKAGE_luci-app-eqos=y
          CONFIG_PACKAGE_luci-app-ssr-plus=n
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=n
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_IPT2Socks=n
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Client=n
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Server=n
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Client=n
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_Obfs=n
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=n
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_Plugin=n
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Xray=n
          CONFIG_PACKAGE_luci-app-wol=n
          CONFIG_PACKAGE_luci-app-wolplus=y

          EOF

          sed -i 's/^[ \t]*//g' ./.config
          cp .config .config.cs

          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-app-easymesh=y
          CONFIG_PACKAGE_luci-app-guest-wifi=y
          # WIFI driver
          CONFIG_PACKAGE_kmod-mt7603=y
          CONFIG_PACKAGE_kmod-mt76x2=y
          CONFIG_PACKAGE_hostapd-common=y
          CONFIG_PACKAGE_wpad-openssl=y
          CONFIG_PACKAGE_kmod-mt7603e=n
          CONFIG_PACKAGE_kmod-mt76x2e=n
          CONFIG_PACKAGE_luci-app-mtwifi=n
          CONFIG_PACKAGE_mt_wifi=n
          EOF
          sed -i 's/^[ \t]*//g' ./.config

      - name: Download package source code
        run: |
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware(OpenSource)
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt-newifi-d2
          path: bin/targets/ramips/mt7621/openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin
      - name: Compile firmware
        run: |
          rm -f ./.config
          mv .config.cs .config
          make defconfig
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt-newifi-d2_cs
          path: bin/targets/ramips/mt7621/openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin
